### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by hadikoub** [viig99/SymSpellCppPy#10]
After installing **SymSpellCppPy** using pip I tried Importing the module but I'm getting this error 
```
root@2428e6bd41d1:/# python3 
Python 3.8.10 (default, Jun  2 2021, 10:49:15) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from SymSpellCppPy import SymSpellPy
Illegal instruction (core dumped)
```
I was installing this inside a docker container. 

Any help?

**Comment by viig99** [comment]
Not sure whats happening here, could be an issue during the installation process, probably something with the gcc version maybe ? gdb logs will be needed for understand the root cause of the issue better.
